### PR TITLE
Ratings images rendering as expected

### PR DESCRIPTION
**Pull request by ccali11**
Ratings Rendering As Expected

### CODE REVIEW

**Comment by CSellers720** [comment]
Wow, this is looking great! I couldn't find a free copy of the font they were using on the original page, but it looks like you're using it. Did you have to download it or did you load it from a URL in your html? I'd like to switch everything over so our components match.

**Comment by ccali11** [comment]
@CSellers720 - Pretty sure I only have the fonts that are accessible in the browser, which the 'Customer Reviews' title of my module is actually slightly different than the font they use on the site. It's close. And then I use avenir for most of the other fonts. The specific CSS I'm using is this; give it a shot and see if we can at least be consistent with our two components:

body {
  background: #F9F9F8;
  font-family: 'Avenir Book',Arial,Helvetica,sans-serif;
  color: #333;
  font-size: 14px;
  line-height: 1.428571429;
}

h1, h2, h3, h4, h5, h6, .h1, .h2, .h3, .h4, .h5, .h6, .h2-s, .h3-s {
  font-family: 'ZapfHumanist601BT-Roman';
  font-weight: 400;
  color: #000;
  text-transform: capitalize;
}

To be clear, I'm not importing any font libraries or hosting any fonts locally. Font Awesome, despite the name, is only responsible only for the icons (I believe), but if you try the css above and it doesn't work, let me know and I'll double check.

**Comment by CSellers720** [comment]
I tried using Avenir Book, but it's not included on my system. I tried sourcing it online and it seemed like they were trying to charge for it. I got a font with similar characteristics and ran with it.

For reference, the font I'm using is Montserrat which I got from google fonts and loaded from a URL in my html file.

**Comment by jonathandavidlewis** [comment]
Nice adding the image, clearly shows the look and feel.

**Pull request merged**
